export const enum OnEventTypeEnum {
  BEFORE_CREATE_SERVICE = 'BEFORE_CREATE_SERVICE',

  CREATE_SERVICE = 'CREATE_SERVICE',

  DISABLE_SERVICE_FROM_NTU = 'DISABLE_SERVICE_FROM_NTU',

  DELETE_SERVICE = 'DELETE_SERVICE',

  UPDATE_SERVICE = 'UPDATE_SERVICE',
}
